import { useState } from 'react';
import axios from 'axios';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const theme = [
  "りんご",
  "バナナ",
  "いちご",
  "みかん",
  "さくらんぼ",
  "お花",
  "くま",
  "ねこ",
  "いぬ",
  "うさぎ",
  "ひよこ",
  "くじら",
  "とら",
  "ぞう",
  "さる",
  "いし",
  "すな",
  "みず",
  "こおり",
  "やま",
  "はし",
  "くつ",
  "ぼうし",
  "リュックサック",
  "ほん",
  "えんぴつ",
  "ノート",
  "けしごむ",
  "テレビ",
  "ラジオ",
  "コンピュータ",
  "おかし",
  "アイスクリーム",
  "ケーキ",
  "ピザ",
  "ハンバーガー",
  "おにぎり",
  "スプーン",
  "フォーク",
  "お皿",
  "コップ",
  "お箸",
  "はし",
  "サッカーボール",
  "バスケットボール",
  "野球",
  "テニス",
  "自転車",
  "バス",
  "電車",
  "飛行機",
  "船",
  "自動車",
  "公園",
  "学校",
  "友達",
  "先生",
  "おじいちゃん",
  "おばあちゃん",
  "お父さん",
  "お母さん",
  "弟",
  "妹",
  "家",
  "部屋",
  "テレビゲーム",
  "おもちゃ",
  "絵本",
  "音楽",
  "映画",
  "時計",
  "雲",
  "風",
  "雨",
  "太陽",
  "星",
  "地球",
  "海",
  "山",
  "花",
  "草",
  "森",
  "川",
  "雪",
  "虹",
  "地面",
  "空",
  "電気",
  "火",
  "雲",
  "雁",
  "カエル",
  "ねずみ",
  "いか",
  "さかな",
  "りゅう",
  "おばけ",
  "ほうき"
]

export default function Home() {
  const [prompt, setPrompt] = useState<string>("");
  const [response, setResponse] = useState<string>("");
  const [response_emotion, setResponse_emotion] = useState<string>("");
  const [response_reply, setResponse_reply] = useState<string>("");
  const randomIndex = Math.floor(Math.random() * theme.length);
  const firstRandomTheme = theme[randomIndex];
  const [randomTheme, setRandomTheme] = useState<string>(firstRandomTheme);
  const [requestCount, setRequestCount] = useState<number>(0);

  const handleReload = () => {
    const randomIndex = Math.floor(Math.random() * theme.length);
    const randomTheme = theme[randomIndex];
    setRandomTheme(randomTheme);
    setPrompt("");
    setResponse_emotion("");
    setResponse_reply("");
    setRequestCount(0);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    if (prompt.includes(randomTheme)) {
      e.preventDefault();
      setResponse_emotion("correct");
      setResponse_reply("正解！！");
    } else {
      e.preventDefault();
      const { data } = await axios.get(`/api/chatgpt?prompt=${prompt}&theme=${randomTheme}`);
      setResponse(data);

      const response_json = JSON.parse(data);
      const judgement: string = response_json.judgement;
      const reply: string = response_json.presenter_reply;
      setResponse_emotion(judgement);
      setResponse_reply(reply);
      setRequestCount(requestCount + 1);
    }
  };

  const handleShowAnswer = () => {
    alert("正解は: " + randomTheme);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          連想ゲーム
        </h1>
        <h2>
          質問回数: {requestCount}
        </h2>
        <div>
          <form className={styles.chatGPT} onSubmit={handleSubmit}>
            <input
              type="text"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
            <button type="submit">送信</button>
          </form>
          {/* <div>{response}</div>
          <div>{response_emotion}</div> */}
          <div>{response_reply}</div>
        </div>
        <button onClick={handleReload}>次の問題へ</button>
        <button onClick={handleShowAnswer}>正解を見る</button>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
